"use client";

import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import "animate.css";
import Navbar from "@/components/Navbar/Navbar";
import Footer from "@/components/Footer/Footer";
import Provider from "./Provider";
import Navbar2 from "@/components/Navbar/Navbar2";
import { usePathname } from "next/navigation";
import { AuthProvider } from "@/components/AuthProvider/AuthProvider";
import { Toaster } from 'react-hot-toast';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const metadata = {
  title: "mPair Technologies Ltd.",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  const pathname = usePathname();
  const useNavbar2 = [
    "/home",
    "/about",
    "/service/robotics-iot",
    "/service/seo",
  ].includes(pathname);

  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <Provider>
          {useNavbar2 ? <Navbar2 /> : <Navbar />}
          <AuthProvider>{children}</AuthProvider>
                  <Toaster position="top-center" reverseOrder={false} />


          <Footer />
        </Provider>
      </body>
    </html>
  );
}
